---
## Management Users and Groups

- name: Check if this is first execution
  tags: first-execution
  ansible.builtin.debug:
    msg: "This is first execution"

- name: Users and Groups management
  tags:
    - groups
    - users
    - config_sudoers
  ansible.builtin.include_tasks: users_groups.yml

- name: Configure ssh access
  tags:
    - ssh_copy
    - ssh_config
  ansible.builtin.include_tasks: ssh.yml

- name: Configure server
  tags:
    - energy
  ansible.builtin.include_tasks: server_config.yml
