---
- name: Include ssh vars
  tags: always
  ansible.builtin.include_vars: vars/ssh.yml

- name: Upload authorized key
  ansible.posix.authorized_key:
    user: "{{ ssh_user }}"
    key: "{{ lookup('file', '../files/' + ssh_user + '.pub') }}"
    state: present
  tags: ssh_copy

- name: Disable root login
  notify:
    - restart ssh
  tags: ssh_config
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^.?PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backup: true


- name: Enable PubkeyAuthentication
  notify:
    - restart ssh
  tags: ssh_config
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '#PubkeyAuthentication'
    line: "PubkeyAuthentication yes"
    state: present
    backup: true
