---
- name: Include var file
  include_vars: vars/users_groups.yml
  tags: always

- name: Create group
  group:
    name: "{{ item.name }}"
    gid:  "{{ item.gid }}"
    local: true
    state: present
  tags: groups
  with_items: "{{ groups_list }}"


- name: create users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    password_lock: "{{ item.password_lock |default(false)|bool }}"
    append: "{{ item.append |default(false)|bool }}"
    groups: "{{ item.groups }}"
    group: "{{ item.group }}"
    shell: "{{ item.shell |default('/bin/bash') }}"
    create_home: "{{ item.create_home|default(false)|bool }}"
    comment: "{{ item.comment }}"
    state: present
  tags: users
  with_items: '{{ users_list }}'

- name: Make users passwordless for sudo in group wheel
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  tags: config_sudoers
