## Docker compose settings
image:
  name: docker.io/eclipse-mosquitto
  pull_policy: always
container_name: mosquitto
restart: unless-stopped

configs:
  mosquitto_users: /mosquitto/config/mosquitto_users
  mosquitto_config: /mosquitto.config

entrypoint: "mosquitto -c {{ configs.mosquitto_config }}"

mosquitto_main:
  path: "{{ dockercompose.path }}/mosquitto"

main_paths:
  config:
    path: "{{ mosquitto_main.path }}/config"

docker_compose:
  project:
    path: "{{ mosquitto_main.path }}/docker-compose"
