---

- name: Include vars
  tags: always
  ansible.builtin.include_vars:
    file: vars/main.yml

- name: Prepare Network packages
  tags: packages_config
  loop: "{{ network_packages }}"
  ansible.builtin.include_tasks:
    include_tasks: "{{ item }}.yml"
