---

- name: Include NGINX vars
  tags: always
  ansible.builtin.include_vars:
    file: vars/nginx.yml

- name: Install NGINX
  tags: always
  notify:
    - restart nginx
  ansible.builtin.package:
    name: nginx
    state: "{{ nginx.version }}"
