---
- name: Testing function
  # become_user: "{{ dockercompose_user }}"
  # become: true
  ansible.builtin.command:
    argv:
      - "whoami"
      - ";"
      - "docker"
      - "run"
      - "hello-world"
    register: test-log-function
    ignore_errors: true

- name: Print the log of the test function
  tags: always
  ansible.builtin.debug:
    var: test-log-function
