---
- name: Include vars
  ansible.builtin.include_vars:
    file: vars/main.yml
  tags: always

- name: Manage docker-compose
  ansible.builtin.include_tasks:
    file: dockercompose/main.yml
  tags:
    - docker-compose

- name: Manage mosquitto
  ansible.builtin.include_tasks:
    file: mosquitto/main.yml
  args:
    apply:
      # become_user: "{{ dockercompose_user }}"
      become: true
  tags:
    - mosquitto

- name: Manage frigate
  ansible.builtin.include_tasks:
    file: frigate/main.yml
  args:
    apply:
      # become_user: "{{ dockercompose_user }}"
      become: true
  tags:
    - frigate

- name: Hello world docker (become testing function)
  ansible.builtin.import_tasks:
    file: hello.yml
  become_user: "{{ dockercompose_user }}"
  become: true
  tags:
    - hello
