---
# handlers file for server-management

- name: Restart ssh
  when: ansible_distribution == "Centos"
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart ssh
  when: ansible_distribution == "Ubuntu"
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart systemd-logind
  when: ansible_distribution == "Ubuntu"
  ansible.builtin.service:
    name: systemd-logind
    state: restarted
