---
- name: Include frigate vars
  ansible.builtin.include_vars:
    dir: frigate
    extensions:
      - yml
  tags: always

- name: Include mosquitto app-config vars
  ansible.builtin.include_vars:
    file: mosquitto/app-config.yml
  tags: always

- name: Delete frigate
  tags: delete
  block:
    - name: Docker compose frigate down
      ansible.builtin.debug:
        msg: "Down frigate..."
      changed_when: true
      notify: 'compose down'

    - name: Flush handlers
      ansible.builtin.meta:
        free_form: flush_handlers

    - name: Delete configs
      loop:
        - "{{ frigate_main.path }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent

- name: Config frigate
  tags: config
  block:
    - name: Create frigate dirs
      loop:
        - "{{ main_paths.media.path }}"
        - "{{ main_paths.database.path }}"
        - "{{ main_paths.config.path }}"
        - "{{ docker_compose.project.path }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ dockercompose_user }}"
        mode: '0755'

    - name: Copy frigate docker_compose template
      ansible.builtin.template:
        src: "{{ frigate_main.path }}/docker-compose/docker-compose.yml.j2"
        dest: "{{frigate_main.path}}/docker-compose/docker-compose.yml"
        owner: "{{ dockercompose_user }}"
        mode: '0644'

    - name: Import Mosquitto users
      ansible.builtin.include_vars:
        dir: mosquitto
        name: app-config.yml

    - name: Copy frigate config config
      ansible.builtin.template:
        src: "{{ frigate_main.path }}/configs/{{item | basename}}"
        dest: "{{ main_paths.config.path}}/{{item | basename | splitext | first}}"
        mode: '0644'
      loop: "{{ lookup('ansible.builtin.fileglob', 'frigate/configs/*', wantlist=True) }}"

##################
# Manage Frigate #
##################

- name: Docker compose frigate up
  ansible.builtin.debug: 
    msg: "Up frigate..."
  changed_when: true
  notify: compose up
  tags: up

- name: Docker compose frigate down
  ansible.builtin.debug: 
    msg: "Down frigate..."
  changed_when: true
  notify: 'compose down'
  tags: down

- name: Docker compose frigate restart
  ansible.builtin.debug: 
    msg: "restart frigate..."
  changed_when: true
  notify: 'compose restart'
  tags: restart