---
###############
# Config vars #
###############
- name: Include frigate vars
  ansible.builtin.include_vars:
    dir: frigate
    extensions:
      - yml
  tags: always

- name: Include mosquitto app-config vars
  ansible.builtin.include_vars:
    file: mosquitto/app-config.yml
  tags: always

##################
# Config Frigate #
##################

- name: Delete frigate
  tags: delete
  block:
    - name: Docker compose frigate down
      ansible.builtin.debug:
        msg: "Down frigate with delete..."
      changed_when: true
      notify: "compose down delete"

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Delete configs
      loop:
        - "{{ frigate_main.path }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent

- name: Config frigate
  tags: config
  block:
    - name: Create frigate dirs
      loop:
        - "{{ main_paths.media.path }}"
        - "{{ main_paths.database.path }}"
        - "{{ main_paths.config.path }}"
        - "{{ docker_compose.project.path }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ dockercompose_user }}"
        mode: "0755"

    - name: Ensure directory structure exists
      ansible.builtin.file:
        path: "{{ main_paths.config.path }}/{{ item.path }}"
        state: directory
        mode: "0755"
        owner: "{{ dockercompose_user }}"
      with_community.general.filetree: "files/frigate/configs/"
      when: item.state == 'directory'

    - name: Ensure files are populated from templates
      ansible.builtin.template:
        src: "files/frigate/configs/config.yml.j2"
        dest: "{{ main_paths.config.path }}/config.yml"
        mode: "0644"
        owner: "{{ dockercompose_user }}"

    - name: Ensure docker-compose file is populated from template
      ansible.builtin.template:
        src: "files/frigate/docker-compose/docker-compose.yml.j2"
        dest: "{{ frigate_main.path }}/docker-compose/docker-compose.yml"
        mode: "0644"
        owner: "{{ dockercompose_user }}"

    - name: Copy directory structure
      ansible.builtin.copy:
        src: "files/frigate/configs/{{ item }}"
        dest: "{{ main_paths.config.path }}"
        owner: "{{ dockercompose_user }}"
        mode: "0744"
      loop:
        - "mocked_videos"
        - "miscellanea"

    - name: Copy frigate docker_compose template
      ansible.builtin.template:
        src: "files/frigate/docker-compose/docker-compose.yml.j2"
        dest: "{{frigate_main.path}}/docker-compose/docker-compose.yml"
        owner: "{{ dockercompose_user }}"
        mode: "0644"

    - name: Import Mosquitto users
      ansible.builtin.include_vars:
        dir: mosquitto
        name: app-config.yml

    #- name: Copy frigate config config
    #  ansible.builtin.template:
    #    src: "files/frigate/configs/{{ item | basename }}"
    #    dest: "{{ main_paths.config.path}}/{{ item | basename | splitext | first }}"
    #    mode: '0644'
    #  loop: "{{ lookup('ansible.builtin.fileglob', 'frigate/configs/*', wantlist=True) }}"

##################
# Manage Frigate #
##################

- name: Docker compose frigate up
  ansible.builtin.debug:
    msg: "Up frigate..."
  changed_when: true
  notify: compose up
  tags: up

- name: Docker compose frigate down
  ansible.builtin.debug:
    msg: "Down frigate..."
  changed_when: true
  notify: "compose down"
  tags: down

- name: Docker compose frigate restart
  ansible.builtin.debug:
    msg: "restart frigate..."
  changed_when: true
  notify: "compose restart"
  tags: restart

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
