---
- name: Include variables for Docker Compose
  ansible.builtin.include_vars:
    file: vars/docker-compose.yml

- name: Install necessary apps
  become: true
  tags: prepare-system
  block:
    - name: Install yum utils
      ansible.builtin.yum:
        name: yum-utils
        state: latest

    - name: Install device-mapper-persistent-data
      ansible.builtin.yum:
        name: device-mapper-persistent-data
        state: latest
    - name: Install selinux container-selinux >= 2:2.74, docker-ce & epel-release 
      ansible.builtin.yum:
        name: "{{ packages }}"
        update_cache: yes
        state: present
      vars:
        packages:
        - https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/container-selinux-2.221.0-1.el9.noarch.rpm
        - docker-ce
        - https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-9.noarch.rpm
      when: ansible_distribution == 'RedHat'

    - name: Install python-pip
      ansible.builtin.yum:
        name: python-pip
        update_cache: true
        state: present

- name: install docker
  become: true
  tags: install
  block:
    - name: Add official Docker GPG key
      rpm_key:
        key: "https://download.docker.com/linux/centos/gpg"
        state: present

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install docker-ce & epel-release
      ansible.builtin.yum:
        name: "{{ packages }}"
        update_cache: true
        state: present
      vars:
        packages:
          - docker-ce
          - epel-release
      when: ansible_distribution == 'CentOS'

    - name: Install docker compose
      pip:
        name: docker-compose
        state: present

    - name: Add users to the Docker group
      user:
        name: "{{ dockercompose_user }}"
        groups: docker
        # append: yes

    - name: Start Docker Daemon
      systemd:
        state: started
        enabled: yes
        name: docker





